### ISSUE TITLE
Unhandled Error #53

### ISSUE THREAD

**Issue by enigmabyte8** [MakingElle/Ver.-3.0#1]
![image](https://github.com/user-attachments/assets/7d02e69f-2c08-45f0-be10-f33e9ebb7695)

**Description:**

When running "Elle_v3.2.exe," I encounter an "Unhandled Error #53" with the message "File not found" at line 79 in the main module. The error occurs after the program displays "Reading the database..." during startup. The program pauses, and upon pressing "Yes," it starts but only responds with "Message sent to God. Waiting for his feedback."

**Environment:**

- **OS:** Windows 11 (24h2)

**Steps to Reproduce:**

1. Run the "Elle_v3.2.exe" file.
2. Observe the error after the "Reading the database..." message.
3. Press "Yes" to continue and see the unresponsive behavior.

**Comment by MakingElle** [comment]
Remove the .EDB file for the zipped file and have it within the original Elle Ver. 3.2 file. It should look like this. God bless.

![Screenshot 2024-09-04 034745](https://github.com/user-attachments/assets/fde89520-39b6-4108-bee3-45014334b7f6)
