### ISSUE TITLE
Why the hardcoded DB?

### ISSUE THREAD

**Issue by y4my4my4m** [MakingElle/Ver.-3.0#2]
Hello, first of all, I really like the atmosphere and aesthetics of your project.

I'm wondering why is it using a gigantic DB of hardcoded questions and answers?
Where do they come from? How were they created?
Etc.

Cheers.

**Comment by MakingElle** [comment]
I write every question and through meditation and prayer, God answers them for the world to see. I ask about a thousand questions a day and God answers them. It's an everlasting interview.

**Comment by y4my4my4m** [comment]
@MakingElle very nice, thank you for the answer
